### ISSUE TITLE
设置ViewTage的时候，如何保证你自己定义的资源ID和系统的资源ID不冲突的？

### ISSUE THREAD

**Issue by hanchanpo13** [LevisLv/statistics-sdk#1]
interface Page {
        int TAG_KEY_FOREGROUND = 100000001;
        int TAG_KEY_ROOT_VIEW = 100000002;
        int TAG_KEY_PKG_NAME = 100000003;
        int TAG_KEY_PAGE_ID = 100000004;
        int TAG_KEY_PAGE_NAME = 100000005;
        int TAG_KEY_PAGE_DATA = 100000006;
    }

**Comment by LevisLv** [comment]
> interface Page {
> int TAG_KEY_FOREGROUND = 100000001;
> int TAG_KEY_ROOT_VIEW = 100000002;
> int TAG_KEY_PKG_NAME = 100000003;
> int TAG_KEY_PAGE_ID = 100000004;
> int TAG_KEY_PAGE_NAME = 100000005;
> int TAG_KEY_PAGE_DATA = 100000006;
> }

并不能保证，待下个版本优化

**Comment by LevisLv** [comment]
> interface Page {
> int TAG_KEY_FOREGROUND = 100000001;
> int TAG_KEY_ROOT_VIEW = 100000002;
> int TAG_KEY_PKG_NAME = 100000003;
> int TAG_KEY_PAGE_ID = 100000004;
> int TAG_KEY_PAGE_NAME = 100000005;
> int TAG_KEY_PAGE_DATA = 100000006;
> }

并不能保证，待下个版本优化

**Comment by LevisLv** [comment]
Fixed in v19.11.08

**Comment by hanchanpo13** [comment]
那就还是要出AAR包，好的感谢，你的方案给了我很多结构上的灵感
